### ISSUE TITLE
Add option to stay logged in for an extended period

### ISSUE THREAD

**Issue by randomouscrap98** [12Me21/sbs2#33]
The API has a short token expiration, it's something like one week. It would be nice if there were an option to set it for like a whole year, like the builtin frontend. I think you just set some kind of expire field on login, and you just need a checkbox. Here um, it's somewhere on this page: https://qcs.shsbs.xyz/api/run/index.html?t=login the function will be like... oh here, found it:
```js
    if(document.getElementById("login-extended").checked)
    {
        loginParam.expireSeconds = LOGINEXPIRELONG;
        console.debug(`LONG token expiration set to: ${loginParam.expireSeconds} seconds`);
    }
```

**Comment by y-ack** [comment]
resolved in https://github.com/12Me21/sbs2/commit/439f9b889d899b8d56301e66bce83752c760f77e

**Comment by randomouscrap98** [comment]
Yay!
