### ISSUE TITLE
Show children of pages SOMEWHERE

### ISSUE THREAD

**Issue by randomouscrap98** [12Me21/sbs2#34]
It's really cool that there's a site tree now, that greatly increases navigation... or at least it would, if the child pages were accessible from the parent. Right now the tree shows only parents, and clicking on the parent brings you to a page that doesn't show the children. For instance, there's a lot more pages in "Off-Topic" than just the few children that show up in the tree, same for Obsolete etc. I don't know how you want to do that, whether it's loading more pages with some + sign in the tree on the search tab, or showing the child and parent pages on the real page when loaded, or something else, but as it is, navigation is still difficult, as we can't really see all the children inside a parent, even though you can navigate to the parent from the tree.

Thank you for adding the tree though

**Comment by y-ack** [comment]
y was thinking that a category view makes sense, and the tree could link to category/id 
which would list child branches and leaves and things instead (and then link to the page view maybe)
